---
- hosts: digitalocean

  tasks: 

  - name: ensure ssh key exists
    user: >
      name={{ ansible_user_id }}
      generate_ssh_key=yes
      ssh_key_file=DO2

  - name: ensure key exists at DigitalOcean
    digital_ocean: >
      state=present
      command=ssh
      name=DO2
      ssh_pub_key={{ lookup('file', '~/DO2.pub') }}
      api_token={{ do_token }}
    register: DO2

  - name: ensure plain instance exists
    digital_ocean: >
      state=present
      command=droplet
      name=plain1
      unique_name=yes
      size_id=512mb
      region_id=nyc1
      image_id=21669205
      ssh_key_ids={{ DO2.ssh_key.id }}
      api_token={{ do_token }}
    register: plain_one

  - debug: msg="IP is {{ plain_one.droplet.ip_address }}"
  - local_action: copy content={{ plain_one.droplet.ip_address }} dest=~/droplet_ip


