#!/bin/bash


#######################################################################################
if [ -z ${TOKEN+x} ]; then echo "Set token first"; exit 1;
fi


#######################################################################################
function show_hosts
{
curl -X GET -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" "https://api.digitalocean.com/v2/droplets" |jq '.droplets[].name'
}


#######################################################################################
function init_proxy_host
{
  ansible-playbook digitalocean-up.yml --extra-vars="do_token=`echo $TOKEN`"

  IP=`cat ~/droplet_ip`
  cat hosts_template |sed "s/IP/$IP/g" > hosts

  echo "Wait for node's ssh"
  until ssh -o "StrictHostKeyChecking=no" -i ~/DO2 -T root@$IP exit # 2>/dev/null
   do
     echo -n '.'
     sleep 5
   done
  echo ''
  ansible-playbook -i hosts squid.yml 
}

#######################################################################################
case $1 in

 plain)
  init_plain_host
  ;;

 docker)
  init_docker_host
  ;;

 proxy)
  init_proxy_host
  ;;

 down)
  ansible-playbook digitalocean-down.yml  --extra-vars="do_token=`echo $TOKEN`"
  ;;

 show)
  show_hosts
  ;;

 *)
  echo " Usage: mkinst plain|docker|proxy|show"
  ;;
esac


